language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
cache: pip
dist: bionic
install:
  - pip install tox-travis codecov
script:
  - tox
after_success:
    - codecov

jobs:
  fast_finish: true
  include:
    - name: Check flake8 on Python 2
      python: 2.7
      env: TOXENV=flake8

    - name: Check flake8 on Python 3
      python: 3.7
      env: TOXENV=flake8

    - name: Check black formatting
      python: 3.7
      env: TOXENV=black

    - name: Check license headers
      python: 3.7
      env: TOXENV=license
